### ISSUE TITLE
concourse terraform creates an improper load balancer

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry-incubator/bosh-google-cpi-release#104]
We used the concourse terraform to create a concourse instance. It deployed perfectly!

However, when we are watching jobs through the browser the jobs were not updating. It wasn't till we reloaded a page we realized a job completed five minutes previously.

After investigation, the HTTP/S load balancer created is not supporting websocket and SSE events correctly. According to the [docs](https://cloud.google.com/compute/docs/load-balancing/http/) these are not supported, unless using TCP/IP load balancer or by setting forwarding rules.

We'd like to help fix this as we are going to hack around the terraform configurations to make it work. Which then null/voids the usefulness of terraform for rolling back nicely.

**Comment by evandbrown** [comment]
Hey @jtarchie, glad to hear the deploy worked! Are you thinking you'd like to see the Terraform manifests updated to use the TCP LB?

**Comment by jtarchie** [comment]
Yes, we have some updates for the terraform scripts to contribute back.

**Comment by jtarchie** [comment]
This hopefully has been resolved in this [PR](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/pull/119)

**Comment by evandbrown** [comment]
Resolved by #119
