### ISSUE TITLE
Project API is nonexistent

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry-incubator/bosh-google-cpi-release#107]
Relevant line: https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blame/95df8c5dac4bb61969d6b4228bd12ffd9845cd02/docs/bosh/README.md#L28

This link does not take me to an API, and there is no such API called 'Project API' that I can search for.

**Comment by evandbrown** [comment]
@jadekler can you attach a screenshot of what you're seeing? That link works for me in 2 different Google accounts. Strange.

**Comment by jadekler** [comment]
@evandbrown It now works! Super, super strange. On our training day we saw nothing. /shrug
