### ISSUE TITLE
Deploying BOSH instructions missing some environment variables

### ISSUE THREAD

**Issue by crhino** [cloudfoundry-incubator/bosh-google-cpi-release#113]
Deploying a BOSH in new google project, following instructions [here](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/bosh/README.md). Love the documentation, very easy to follow and setup!

We got all the way to [deploying bosh](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/bosh/README.md#deploy-bosh), when we failed to `bosh-init` because the `manifest.yml` file did not have the `network`, `subnetwork`, `zone`,  and `ssh_key_path` environment variables to interpolate in the erb file.

We ended up manually setting those env vars and getting the manifest in a good state, but I imagine there might be a better, automatic way of finding those values through the `gcloud` CLI.

**Comment by johnsonj** [comment]
Thanks @crhino. I've added some checks to the manifests so you'll know it's missing the env variables. 

Happy to check out a sketch of how to accomplish it in an easier clear way! Closing this issue for now.

**Comment by krishnachaitanyareddy** [comment]
Could you add network, subnetwork environment variables to the doc
