### ISSUE TITLE
Default Application Security Groups are wide open

### ISSUE THREAD

**Issue by davidjahn** [cloudfoundry-incubator/bosh-google-cpi-release#129]
In the [cloudfoundry example](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/cloudfoundry/manifest.yml#L1022-L1025), the application security groups are wide open. The [recommended](https://github.com/cloudfoundry/cf-release/blob/0f31531424a0f1c22d78d56be8885e4c138e3c30/templates/cf.yml#L1548-L1568) groups disallow internal networks. This is very important because, as currently configured, 1) containers can see host metadata from the google metadata server, and 2) containers can see the entire bosh subnet, including internal components that should not be viewable to host applications.

**Comment by johnsonj** [comment]
will be fixed by #252
