### ISSUE TITLE
Concourse example Error - VM failed to create: Backend Service "concourse" does not exist: <nil cause>

### ISSUE THREAD

**Issue by matthewcosgrove** [cloudfoundry-incubator/bosh-google-cpi-release#134]
I have been working through https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/tree/master/docs/concourse and when its creating the web VM it fails with `VM failed to create: Backend Service "concourse" does not exist: <nil cause>`

> Done creating missing vms > db/0 (a9cdb68d-9f11-4bea-af69-750c9f390e11) (00:01:01)
> Done creating missing vms > worker/0 (f3ca4d71-6503-4545-b446-aa47e6395426) (00:01:01)
> Failed creating missing vms > web/0 (f06432bb-1275-44ff-ad86-b55d0eda9697): VM failed to create: Backend Service "concourse" does not exist: <nil cause> (00:15:01)
> Failed creating missing vms (00:15:01)

Codewise, this relates to https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/e84f61b28ec0a98cff7f1628f7d930f598f939fc/src/bosh-google-cpi/google/backendservice_service/google_backendservice_service.go#L122

Its clearly expecting a backend service configured but having followed the documented set up from the [README.md](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/concourse/README.md) if I subsequently run `gcloud compute backend-services list` it returns `Listed 0 items`. Any ideas what might be missing here?

**Comment by ebabani** [comment]
Hey @matthewcosgrove , check out this PR to fix this issue.

https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/pull/128

**Comment by matthewcosgrove** [comment]
Great thanks, that fixes it for me
