### ISSUE TITLE
retry non-mutable connection requests

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-google-cpi-release#135]
definitely can retry dial failures. probably should retry a lot more.

+++
CPI error 'Bosh::Clouds::CloudError' with message 'Creating disk: Failed to find Google Instance 'vm-xxx': Get https://www.googleapis.com/compute/v1/projects/xxx/aggregated/instances?alt=json&filter=name+eq+.%2Avm-xxx: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 173.194.74.84:443: i/o timeout' in 'create_disk' CPI method
+++

cc @dsboulder @ljfranklin

**Comment by ljfranklin** [comment]
Random implementation detail that I learned about recently, errors from the `net` package have `netErr.Temporary()` and `netErr.Timeout()` methods to let you know the error is retryable: https://golang.org/pkg/net/#Error.

**Comment by evandbrown** [comment]
Just released [25.7.1](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/releases/tag/v25.7.1). Should be available on bosh.io shortly!
