### ISSUE TITLE
IAM command does not accept multiple roles

### ISSUE THREAD

**Issue by johnsonj** [cloudfoundry-incubator/bosh-google-cpi-release#142]
This snippet in the Cloud Foundry doc attempts to add multiple roles in a single command. This does not work and ends up only adding the last role.

```
gcloud projects add-iam-policy-binding ${project_id} \
    --member serviceAccount:cf-component@${project_id}.iam.gserviceaccount.com \
    --role "roles/editor" \
    --role "roles/logging.logWriter" \
    --role "roles/logging.configWriter"
```

This prevents the google-fluentd agent from writing logs out of the box.

**Comment by evandbrown** [comment]
Fixed. Thanks for reporting!

**Comment by Shrashti** [comment]
Hi, this command is not working for me. I am trying to bind multiple roles in my service account. only the last role is getting bind.

```
	gcloud projects add-iam-policy-binding ${PROJECT_ID} --member \
  	serviceAccount:${SERVICE_ACCOUNT_EMAIL} \
  	--role "roles/storage.admin" 
	--role "roles/bigquery.user"
```

**Comment by josephlewis42** [comment]
Hi @Shrashti it looks like the `gcloud` command can only accept one `--role` at a time so you'll have to call the command multiple times for each role you'd like to add to the account.

```
	gcloud projects add-iam-policy-binding ${PROJECT_ID} --member \
  	serviceAccount:${SERVICE_ACCOUNT_EMAIL} \
  	--role "roles/storage.admin"

	gcloud projects add-iam-policy-binding ${PROJECT_ID} --member \
  	serviceAccount:${SERVICE_ACCOUNT_EMAIL} \
	--role "roles/bigquery.user"
```

If you found that snippet in the documentation for the CPI I'd be happy to get it fixed.

Cheers!
\- Joseph

**Comment by tjann** [comment]
Thanks for clarifying, @josephlewis42 . I think it could be good to make this requirement explicit in the documentation even if the documentation doesn't have the "wrong" snippet. Also tried the exact same thing as the two above.

**Comment by leonardara** [comment]
oh my god, cannot believe this, i instinctively used multiple `--role` and this eating me the whole afternoon to trace the whole authentication chain to figure out where is gong wrong.....

**Comment by BenJackGill** [comment]
There is no mention of this in the docs for [creating a service account](https://cloud.google.com/iam/docs/service-accounts-create#creating). It only shows how to add a single role, and says nothing about needing to do it multiple times to add extra roles.

**Comment by BenJackGill** [comment]
Sorry I commented in the wrong place :/

**Comment by darkn3rd** [comment]
Adding multiple service accounts through several commands will fail.  You'll run into errors like this:

```
ERROR: (gcloud.projects.add-iam-policy-binding) RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Write requests' and limit 'Write requests per minute' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:XXXXXXXXXX'.
```

Thus this is more than just a documentation bug, the gcloud will actually fail.

**Comment by ArielDemidov** [comment]
Damn, such feature would be so helpful because then you get a lot of responses from each command called which is just weird resource wise.
