### ISSUE TITLE
Bosh init should handle it better when the default account is missing

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry-incubator/bosh-google-cpi-release#144]
If the default project account has been deleted, using service_scopes in your bosh director manifest results in an obscure error:
```
CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::VMCreationFailed","message":"VM failed to create: Google Operation 'operation-1484172723550-545d8e3f8f730-654d03c4-17847194' finished with an error: The resource '246559366663-compute@developer.gserviceaccount.com' of type 'serviceAccount' was not found.\n","ok_to_retry":true}
```
This error message is unclear, particularly because the credentials which also need to be specified in the manifest may be associated with another account altogether.

The default service_account for the bosh-google-cpi-release [is set to "default" if it is not proactively set by the bosh manifest](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/e84f61b28ec0a98cff7f1628f7d930f598f939fc/src/bosh-google-cpi/vendor/google.golang.org/cloud/compute/metadata/metadata.go#L425), so this will happen anytime you use `service_scopes` instead of a `service_account`, which is exactly what the `bosh-bootloader` does in its bosh-init manifest today.

cc: @ljfranklin @JesseTAlford @evanfarrar

**Comment by johnsonj** [comment]
dup #121
