### ISSUE TITLE
Handle propagation of tags and labels

### ISSUE THREAD

**Issue by evandbrown** [cloudfoundry-incubator/bosh-google-cpi-release#156]
On March 7, 2017, VM tags will no longer propagate to VM labels with empty values. This may affect how the CPI labels resources.

**Comment by johnsonj** [comment]
This is now causing a failure in CI for this [test](https://sourcegraph.com/github.com/cloudfoundry-incubator/bosh-google-cpi-release@2a32b8b71e37d4feea2285598b6d2c0c103f8e64/-/blob/src/bosh-google-cpi/integration/vm_test.go#L98)
