### ISSUE TITLE
Deleting stemcell fails if image does not exist

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry-incubator/bosh-google-cpi-release#162]
When deleting a stemcell (e.g. during `bosh delete-env`) if the image has already been removed then the teardown fails with the following error:

```
Deleting deployment:
  Deleting stemcell from cloud:
    CPI 'delete_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Deleting stemcell 'stemcell-ab5f5573-62d5-4f72-6620-3ab8f1aed3cf': Google Image 'stemcell-ab5f5573-62d5-4f72-6620-3ab8f1aed3cf' does not exists: \u003cnil cause\u003e","ok_to_retry":false}

Exit code 1
```

I would expect this to succeed if the image is gone, because that's exactly the operation we're trying to achieve.

For context, this is a problem for us as we accumulate lots of images because we spin up lots of bosh environments in our account, and each deployment results in a new image (`stemcell-<guid>`). To avoid hitting the limit we asynchronously delete the images, but then our tear down of the bosh director fails with the above error.

cc @cppforlife

**Comment by johnsonj** [comment]
this will be fixed in the next release
