### ISSUE TITLE
mysterious stream error during create_vm cpi call

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-google-cpi-release#167]
```
Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'stemcell-6577b498-26b2-4f43-50a0-372c03558aee':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating vm: Failed to find Google Image 'stemcell-6577b498-26b2-4f43-50a0-372c03558aee': Get https://www.googleapis.com/compute/v1/projects/cf-sandbox-lsantos/global/images/stemcell-6577b498-26b2-4f43-50a0-372c03558aee?alt=json: stream error: stream ID 1; PROTOCOL_ERROR","ok_to_retry":false}
```

ran into this error twice in last two days. rerunning bosh create-env (bosh-init deploy) makes the error go away but we should probably retry.

**Comment by cppforlife** [comment]
```
Deploying:
  Deleting existing instance 'unknown/0':
    Deleting vm in the cloud:
      CPI 'delete_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Deleting vm 'vm-a2a5b6f9-0cdc-4a65-4656-9af33914411a': Failed to find Google Instance 'vm-a2a5b6f9-0cdc-4a65-4656-9af33914411a': Get https://www.googleapis.com/compute/v1/projects/cf-bosh-concourse/aggregated/instances?alt=json\u0026filter=name+eq+.%!A(MISSING)vm-a2a5b6f9-0cdc-4a65-4656-9af33914411a: stream error: stream ID 1; PROTOCOL_ERROR","ok_to_retry":false}
```

**Comment by charleshansen** [comment]
We have seen this error many times on routing while trying to deploy a new env. Agreed that error does eventually go away if you run enough times.

**Comment by johnsonj** [comment]
Released [v25.9.0](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/releases/tag/v25.9.0) with Golang 1.8.1 to address HTTP/2 issues. Please re-open this bug if you hit the mysterious PROTOCOL_ERROR.

**Comment by xtreme-gavin-enns** [comment]
I'm seeing this error repeatedly right now. I thought it was only happening in concourse, since I was able to deploy from my workstation. But then it started failing there too. With some persistence I was able to get it to succeed from my workstation again. It's never worked from concourse (hosted in the pivotal pizza boxes in sf).

**Comment by johnsonj** [comment]
@xtreme-gavin-enns can you confirm you're using the latest CPI: [v25.9.0](https://bosh.io/releases/github.com/cloudfoundry-incubator/bosh-google-cpi-release?version=25.9.0)

**Comment by xtreme-gavin-enns** [comment]
We're still using 25.6.2

I'll bump that and see if it helps

**Comment by xtreme-gavin-enns** [comment]
Apologies. Reading comprehension fail.
