### ISSUE TITLE
Running Into Static Address Quota Limits

### ISSUE THREAD

**Issue by nicks451** [cloudfoundry-incubator/bosh-google-cpi-release#168]
I'm running the terraform apply step and I'm running into 

`google_compute_address.cf-tcp: Error creating address: googleapi: Error 403: Quota 'STATIC_ADDRESSES' exceeded. Limit: 1.0, quotaExceeded`

I was able to do this without any problems last week but needed to destroy everything and set it up inside a new project. So I'm not sure if the quota decreased for some reason in the past 4 days or if something changed because we're on the free trial. Any ideas?

**Comment by johnsonj** [comment]
The limit looks oddly low, my default projects have a quota of 7. I'll try to check with a fresh trial account.

Can you increase your quota? The Cloudfoundry deployment requires 2 IPs (for HTTP, TCP load balancers). See the [quotas page](https://console.cloud.google.com/compute/quotas) and update the quota for `Static IP addresses us-east1`

**Comment by nicks451** [comment]
Okay just had the account owner change us from a trial account to a full account and we have 7 static ip addresses in our quota. 

Thanks
