### ISSUE TITLE
Update to Golang 1.8.1

### ISSUE THREAD

**Issue by johnsonj** [cloudfoundry-incubator/bosh-google-cpi-release#185]
Issues with HTTP requests seem to be resolved by latest Go release.

Related #183 #167

**Comment by johnsonj** [comment]
@cunnie / @ljfranklin Do you have access to the Docker image used in CI? It's still [using 1.6](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/ci/docker/bosh-google-cpi-boshrelease/Dockerfile#L18)

**Comment by johnsonj** [comment]
Re-opened to track docker image

**Comment by cunnie** [comment]
Good catch. I think this is the upstream docker image here: https://hub.docker.com/r/boshcpi/gce-cpi-release/

I've re-opened our [Tracker](https://www.pivotaltracker.com/story/show/145703989) to include a task to update the docker image to 1.8

**Comment by cunnie** [comment]
@johnsonj if you give us your Docker userid, we'll upgrade you so you can push the image yourself in the future.

In the meantime, @cdutra and I will make the change & push.

**Comment by johnsonj** [comment]
Thank you! It's `jrjohnsongoog`

**Comment by cunnie** [comment]
You've been added — woohoo! You'll be able to push to [boshcpi/gce-cpi-release](https://hub.docker.com/r/boshcpi/gce-cpi-release/) in a pinch.

The image has been upgraded, **closing issue**. New images can be seen here: https://hub.docker.com/r/boshcpi/gce-cpi-release/tags/

Thanks @johnsonj for all your help these last few days — @cdutra and I really appreciate it.
