### ISSUE TITLE
Failure to cross-compile the release

### ISSUE THREAD

**Issue by dumbbell** [cloudfoundry-incubator/bosh-google-cpi-release#195]
Hi!

I'm trying to deploy a BOSH directory to GCP using the following command:
```
bbl --debug up --iaas gcp --name director-jpedron --gcp-region europe-west1 \
  --gcp-zone europe-west1-d --gcp-service-account-key ../bosh-bootloader.key.json \
  --gcp-project-id cf-rabbitmq-core
```

I'm running it from a FreeBSD workstation, but it fails with the following error:
```
Installing CPI:
  Compiling job package dependencies for installation:
    Compiling job package dependencies:
      Compiling package:
        Running command: 'bash -x packaging', stdout: '', stderr: '+ set -e
+ set -u
++ uname
++ tr '[:upper:]' '[:lower:]'
+ PLATFORM=freebsd
++ ls -r 'golang/go*.freebsd-*'
++ sed 's/golang\/go\(.*\)\.freebsd-amd64.tar.gz/\1/'
++ head -1
ls: golang/go*.freebsd-*: No such file or directory
+ GOLANG_VERSION=
+ tar xzvf /home/dumbbell/.bosh/installations/f465085d-f63c-4aba-500c-c236b6f17aa4/tmp/bosh-release-pkg783787239/golang/go.freebsd-amd64.tar.gz
tar: Error opening archive: Failed to open '/home/dumbbell/.bosh/installations/f465085d-f63c-4aba-500c-c236b6f17aa4/tmp/bosh-release-pkg783787239/golang/go.freebsd-amd64.tar.gz'
':
          exit status 1

Exit code 1
```

If I understand correctly how this release is built:
1. It picks one of the Go distributions embedded in the release (one for Linux/amd64, one for OS X/amd64); see [`packages/golang/packaging`](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/packages/golang/packaging#L5-L9).
2. It uses that Go distribution to build `bosh-google-cpi`; see [`src/bosh-google-cpi/Makefile`](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/src/bosh-google-cpi/Makefile#L4-L5).

And it does all this on the host running `bbl up`.

In my case, it can't pick a Go distribution because there is none for FreeBSD embedded. But after making it think it's Linux, it tried to run the Linux' `go` executable. The Linux emulation isn't good enough and the compiler segfaults. Anyway, I'm not sure if it would have produced a Linux or a FreeBSD native executable.

First, am I correct so far?

If yes, it looks like the build process doesn't fully support cross-compilation. I don't understand how it works when the build host is OS X, but it works fine for my colleague using this system. I guess the embedded OS X Go distribution somehow produces Linux executables, but how?. Could someone please clarify this?

Based on that incomplete understanding, the build process shouldn't rely on the embedded Go distributions to compile `bosh-google-cpi` on the build host. Instead it could use the native Go distribution (provided by any external way) and cross-compile it for the target.

What do you think? Once I better understand what's going on, I would be happy to prepare a patch, given I use a system which is currently unsupported.

**Comment by johnsonj** [comment]
You're correct that we use an embedded version of go to build the CPI. This is inline with the philosophy of BOSH to bring all your dependencies along with you. Relying on a system supplied compiler means I may build with Go 1.8.1 on my machine and you build with 1.7 on yours (which is a [real problem](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/issues/167)).

[Here's](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/packages/golang/packaging) where we select the go version we use. The proper way to add FreeBSD cross compilation support would be to update that script to use the proper binary (from [golang](https://golang.org/dl/)). Happy to review a patch around that. You won't be able to upload the updated binary blob to our release blobstore but I will take care of that if the rest of the change is all set.

**Comment by dumbbell** [comment]
Thank you for the quick answer!

Once the appropriate Go distribution is added to the release, how do you handle the cross-compilation? Because I suppose the OS X `go` produces a Linux executable in the end to run on a Linux stemcell, no?

It's more than possible that I'm missing something here!

**Comment by johnsonj** [comment]
The CPI will be used for bosh-init which runs on your local machine (not sure what it's called in the new bosh CLI). That will be used to deploy a director VM which will rebuild the CPI (once again) producing a Linux binary.

**Comment by johnsonj** [comment]
Closing due to age. Please re-open if you plan on contributing this.
