### ISSUE TITLE
ephemeral_external_ip must be true for Director deploy

### ISSUE THREAD

**Issue by henryaj** [cloudfoundry-incubator/bosh-google-cpi-release#198]
We've found that setting `ephemeral_external_ip` when deploying a BOSH Director to GCP gives an inoperable Director - when we try to upload stemcells, the upload always fails stating connectivity issues with Google Cloud Storage. Setting `ephemeral_external_ip` to true fixes the problem.

Is this the expected behaviour? If so, I'm happy to amend the docs to make this clearer.

Henry

(cc @kirederik)

**Comment by johnsonj** [comment]
More generally we need access to the internet or a project with [Private Google Access](https://cloud.google.com/compute/docs/private-google-access/private-google-access) enabled. We could probably use an update to the docs that includes that sort of info.

Our reference deployment uses NAT ([route](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/bosh/main.tf#L50), [instance](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/bosh/main.tf#L198)) to accomplish this. An `ephemeral_external_ip` will do this as well but we don't advise exposing anything that's not serving traffic.
