### ISSUE TITLE
Proposed changes to docs/bosh/README.md

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bosh-google-cpi-release#209]
I've been writing up a blog post on deploying a GCP bosh + the example zookeeper release from https://github.com/cloudfoundry/bosh-deployment and much of the blog post http://www.starkandwayne.com/blog/p/8fc7f130-2b89-4f91-807f-8840a046bc78/ is "follow the cpi readme but I had to make the following changes". I'd prefer to merge this all back into the docs/bosh/README.md here; and then also into https://bosh.io/docs/init-google.html later.

Summary of proposed changes:

* Use `bosh2` and https://github.com/cloudfoundry/bosh-deployment instead of old `bosh-init` and the erb manifest.yml
* I needed to use `GOOGLE_APPLICATION_CREDENTIALS` as `export GOOGLE_CREDENTIALS=$(cat ~/terraform.key.json)` fails for me
* It seemed odd to assume that someone has `docker` installed but doesn't/can't get terraform CLI installed; so I reverted to simple direct terraform commands (the `docker run` alternates seem a lot more complex)
* Some pretty pictures of GCP dashboard
* Deploy zookeeper as a demo

/cc @johnsonj @cppforlife

**Comment by johnsonj** [comment]
/cc @evandbrown to talk to why terraform is in invoked via docker

Awesome! So great to see Google + BOSH, especially something outside of the more studied realm of Cloud Foundry. 

* `bosh2` is merged into develop. We can promote this as part of closing this issue. 
* `GOOGLE_APPLICATION_CREDENTIALS=~/terraform.key.json` vs `export GOOGLE_CREDENTIALS=$(cat ~/terraform.key.json)`: Fails I'm assuming means terraform didn't pick up any credentials? No guess off the top of my head what would cause that. It is a [supported](https://github.com/terraform-providers/terraform-provider-google/blob/95e72d513e53652cc0217061fee405ff703b1ce9/google/provider.go#L20) value there. But if we end up ripping out docker `GOOGLE_APPLICATION_CREDENTIALS` would be a more idiomatic way to go anyways. 

I think the pictures/zookeeper part is probably best suited for the blog post, or contributing the Zookeeper stuff as it's own `docs/zookeeper/..` like we have for Cloud Foundry. My concern with baking in console images is that UI changes and the commands should do the talking for this specific doc.   

I'd love to move to pointing to core docs for our deployment. At the moment I don't think there is another canonical 'start from 0, get a bosh director on GCP'. I believe the bosh.io doc assumes infrastructure is already there. @cppforlife is that level of documentation on your roadmap?

**Comment by evandbrown** [comment]
Hey @drnic! Thanks for the detailed proposal.

Regarding this point:

> It seemed odd to assume that someone has docker installed but doesn't/can't get terraform CLI installed; so I reverted to simple direct terraform commands (the docker run alternates seem a lot more complex)

The docs are designed to use [Cloud Shell](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/bosh/README.md#setup), where Docker is present but Terraform is not. We were aiming for simplest getting started experience and went this route to avoid Terraform install instructions.

> I needed to use GOOGLE_APPLICATION_CREDENTIALS as export GOOGLE_CREDENTIALS=$(cat ~/terraform.key.json) fails for me

I just tested this (in Cloud Shell per the setup instructions) and it worked fine. Possibly an older Terraform version on your end?

**Comment by evandbrown** [comment]
Sounds like @johnsonj has the `bosh2` pieces in the pipeline. I'd love to include the zookeeper tutorial when that's complete, following the [Deploying other software](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release#deploy-other-software) model that's in the readme today (and is currently limited to Cloud Foundry). To Jeff's point, this would be a separate doc in `docs/zookeeper`. I think the pretty pictures are great to include there as well.

Thanks again for taking the time to do this!

**Comment by johnsonj** [comment]
Closing due to age. Please re-open if it's still relevant. We've got the bosh2 stuff done and planning on doing #251 for bosh-deployment. Zookeeper docs would be neat!
