### ISSUE TITLE
sshgen

### ISSUE THREAD

**Issue by phopper-pivotal** [cloudfoundry-incubator/bosh-google-cpi-release#214]
can docs be updated to indicate for user to not set a passphrase when running 

```$ ssh-keygen -t rsa -f ~/.ssh/bosh -C bosh```

otherwise this error occurs

````Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'stemcell-38b9970b-01a6-4ea0-60e4-8ab781375a4b'... Finished (00:00:53)
  Waiting for the agent on VM 'vm-b4cc23d5-9f2a-427c-76f9-0050fb2d395e' to be ready... Failed (00:00:00)
Failed deploying (00:00:53)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Waiting until instance is ready:
        Starting SSH tunnel:
          Parsing private key file '/home/phopper/.ssh/bosh':
            asn1: structure error: tags don't match (16 vs {class:3 tag:28 length:107 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2```

**Comment by dpb587-pivotal** [comment]
Hi - can you be more specific about which docs you're referring to? The docs I see in the repo do call out that a password-less SSH key is needed ([example](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/PR-boshio-checksum/docs/bosh/README.md#deploy-bosh)).

**Comment by phopper-pivotal** [comment]
https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/bosh/README.md

ok maybe change both links to be passphrase less. on sshkey-gen its a passcode. with little sleep it does equate directly;

```Enter passphrase (empty for no passphrase): 
Enter same passphrase again: ```

**Comment by johnsonj** [comment]
any idea on how to make a 1-liner that doesn't prompt for a password? it's problematic for sure

**Comment by dpb587-pivotal** [comment]
ssh-keygen accepts an empty -P (passphrase) option, so something like the following if you want to recommend it...

    ssh-keygen -t rsa -P '' -C bosh -f ~/.ssh/bosh

**Comment by evandbrown** [comment]
I think `-P` is for the old passphrase. This should silence the whole thing: `ssh-keygen -t rsa -f ~/.ssh/bosh -C bosh -q -N ""`

I'll update the doc...

**Comment by phopper-pivotal** [comment]
thank you @evandbrown @dpb587-pivotal 

destroyed 2 environments last night thinking wth

finally got smart with sleep and set as ""

**Comment by dpb587-pivotal** [comment]
Interesting - I've always used `-P`, but you're right, `-N` is more correct. Thanks for updating the docs.
