### ISSUE TITLE
Incurring an error (can't find Ruby) when executing the Deploy the new manifest to create a BOSH Director step

### ISSUE THREAD

**Issue by JavaFXpert** [cloudfoundry-incubator/bosh-google-cpi-release#245]
Hello,

I have reached the "Deploy the new manifest to create a BOSH Director" step in this document:
[https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/tree/master/docs/concourse](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/tree/master/docs/concourse)

but when executing the following command:
`bosh-init deploy manifest.yml`

I get the following output with an error message that Ruby can't be found:
```
[jamesweaver@bosh-bastion-concourse google-bosh-director]$ bosh-init deploy manifest.yml
Deployment manifest: '/home/jamesweaver/google-bosh-director/manifest.yml'
Deployment state: '/home/jamesweaver/google-bosh-director/manifest-state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:02)
  Downloading release 'bosh-google-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-google-cpi'... Finished (00:00:02)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:04)

Started installing CPI
  Compiling package 'golang/b7c20853a73ad56fad8d60b980503e22d3ac7f43'... Finished (00:00:00)
  Compiling package 'bosh-google-cpi/2334a22dc4536f3bd86a8cd97e0127a5dfb86249'... Finished (00:00:00)
  Installing packages... Finished (00:00:03)
  Rendering job templates... Failed (00:00:00)
Failed installing CPI (00:00:03)

Command 'deploy' failed:
  Installing CPI:
    Rendering and uploading Jobs:
      Rendering job templates for installation:
        Rendering templates for job 'google_cpi/134a472ce3b5764dcaf2de5636b34c8d1560286d':
          Rendering template src: bin/cpi.erb, dst: bin/cpi:
            Rendering template src: /home/jamesweaver/.bosh_init/installations/fc7d9664-f590-4a5c-6260-f634546f32da/tmp/bosh-init-release880157659/extracted_jobs/google_cpi/templates/bin/cpi.erb, dst: /home/jamesweaver/.bosh_init/installations/fc7d9664-f590-4a5c-6260-f634546f32da/tmp/rendered-jobs940263743/bin/cpi:
              Running ruby to render templates:
                Starting command 'ruby /home/jamesweaver/.bosh_init/installations/fc7d9664-f590-4a5c-6260-f634546f32da/tmp/erb-renderer682624914/erb-render.rb /home/jamesweaver/.bosh_init/installations/fc7d9664-f590-4a5c-6260-f634546f32da/tmp/erb-renderer682624914/erb-context.json /home/jamesweaver/.bosh_init/installations/fc7d9664-f590-4a5c-6260-f634546f32da/tmp/bosh-init-release880157659/extracted_jobs/google_cpi/templates/bin/cpi.erb /home/jamesweaver/.bosh_init/installations/fc7d9664-f590-4a5c-6260-f634546f32da/tmp/rendered-jobs940263743/bin/cpi':
                  exec: "ruby": executable file not found in $PATH
```

I tried `which ruby` to find where the ruby executable is located but it results in the following:
`/usr/bin/which: no ruby in (/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/jamesweaver/bin)`

Any ideas on how to proceed?

Thanks,
James Weaver

**Comment by dpb587-pivotal** [comment]
Hi - as part of the deployment process, `create-env` will render some templates which require Ruby/ERB. Sounds like you need to add a few of the OS-specific packages referenced [here](http://bosh.io/docs/cli-env-deps.html). Try that out, and let us know if it helps.

**Comment by johnsonj** [comment]
Our startup script is probably out of date and broken due to changes in packages.

I recommend following [this guide to install concourse with bbl](https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/concourse-gcp.md) over our guide. I plan on updating our docs to point there.

**Comment by johnsonj** [comment]
Hi @JavaFXpert - any luck getting concourse installed?

**Comment by JavaFXpert** [comment]
Jeff,

Thanks for checking up. I made it farther thanks to your advice, but got stuck on the deploy step. I’ll forward an email that contains relevant info.

Regards,
James (Jim) Weaver

**Comment by JavaFXpert** [comment]
Jeff,

Here is the issues page that contains information on where I'm stuck.

https://github.com/cloudfoundry/bosh-bootloader/issues/233

Thanks,
James Weaver


On Mon, Feb 12, 2018, at 12:52 PM, Jeff Johnson wrote:
> Hi @JavaFXpert[1] - any luck getting concourse installed?


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/javafxpert
  2. https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/issues/245#issuecomment-365004961

**Comment by johnsonj** [comment]
Closing as the bbl issue was eventually resolved
