### ISSUE TITLE
Changed disk to boot_disk and added  initialize_params to main.tf

### ISSUE THREAD

**Issue by jasonbisson** [cloudfoundry-incubator/bosh-google-cpi-release#259]
I'm not sure if I pulled the wrong file, but terraform apply failed until the updates were made.

Thanks,

Jason

**Comment by johnsonj** [comment]
Looks like we fixed this for our [bosh](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/bosh/main.tf) doc but not [concourse](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/concourse/main.tf).

Thanks for identifying this!
