### ISSUE TITLE
Error fetching token when setting metadata

### ISSUE THREAD

**Issue by lflux** [cloudfoundry-incubator/bosh-google-cpi-release#268]
Hi,

On an PCF 2.1 environment with director 265.2.0 using  bosh-google-cpi 27.0.0, we're seeing VM creation sometimes fail with an error message that it can't fetch the OAuth token:

Task 101 | 19:17:31 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'Setting metadata for vm 'vm-088e6443-1d2b-43fb-701b-771f95b16ed4': Failed to find Google Instance 'vm-088e6443-1d2b-43fb-701b-771f95b16ed4': Get https://www.googleapis.com/compute/beta/projects/cf-toolsmiths-pool-us-2/aggregated/instances?alt=json&filter=name+eq+.%2Avm-088e6443-1d2b-43fb-701b-771f95b16ed4: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 108.177.112.84:443: i/o timeout' in 'set_vm_metadata' CPI method

We've seen this happen multiple times against the same environment in us-central1, but we're not sure if this is widespread. Is there retry logic in the token fetching?

**Comment by evandbrown** [comment]
Arghhhh, that's annoying. We are doing retries, [here](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/b32fcf7e94d390bd6e340b1e07fd9f4899370b51/src/bosh-google-cpi/google/client/google_client.go#L71-L76). I added that after I saw the on-host metadata server (169.254.169.254) fail occasionally (it solved that problem). The [`RetryTransport`](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/b3be0d4d544d7edcff87f129eb6cd12ab8ec4692/src/bosh-google-cpi/google/client/retry.go#L50) should handle this error, which looks like a network problem connecting to Google's oauth2 token exchange endpoint (could be the endpoint, but probably some transient issue with networking in a zone).

I hardcoded 3 retries, which would span...[~1.4 seconds](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/b3be0d4d544d7edcff87f129eb6cd12ab8ec4692/src/bosh-google-cpi/google/client/retry.go#L46). Wait, what? That probably worked when the instance metadata server failed, but it's not nearly enough for situations like this one.

Ultimately I'd like to make the retry count configurable, but we still need to find a sane default. @lflux , what do you think about...10? That's ~3m30s (https://play.golang.org/p/AeZ9-witSNf)

We also need to add logging for each try.

**Comment by lflux** [comment]
I guess it comes down to how long these transients normally right themselves within. 3 minutes is probably acceptable, maybe if you turn down the constant somewhat to 100ms you get retries a little more often (see https://play.golang.org/p/0KbdgfJCQJt)

I'd really appreciate logging for the retries as it adds insight to me as an operator that the CPI is in fact retrying.

**Comment by voelzmo** [comment]
I can't re-open the ticket, but: we're using CPI 27.0.1 and this happened multiple times in the last few days:
```
 Error: CPI error 'Bosh::Clouds::CloudError' with message 'Deleting vm 'vm-883956d6-0a95-4075-5687-93f616db0598': Failed to find Google Instance 'vm-883956d6-0a95-4075-5687-93f616db0598': Get https://www.googleapis.com/compute/v1/projects/sap-gcp-hcp-cf-live-us30/aggregated/instances?alt=json&filter=name+eq+.%2Avm-883956d6-0a95-4075-5687-93f616db0598: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 173.194.194.84:443: i/o timeout' in 'delete_vm' CPI method
```

```
Error: CPI error 'Bosh::Clouds::CloudError' with message 'Attaching disk 'disk-78848cfc-9e37-4c42-6e35-30157df20fb0' to vm 'vm-5d718bac-126c-43f9-5178-d7bc1593cd31': Failed to find Google Disk 'disk-78848cfc-9e37-4c42-6e35-30157df20fb0': Get https://www.googleapis.com/compute/v1/projects/sap-gcp-hcp-cf-live-us30/aggregated/disks?alt=json&filter=name+eq+.%2Adisk-78848cfc-9e37-4c42-6e35-30157df20fb0: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 74.125.124.84:443: i/o timeout' in 'attach_disk' CPI method
```

**Comment by voelzmo** [comment]
@evandbrown additional information: I don't find any occurence of `RetryTransport` in the task's debug logs

**Comment by voelzmo** [comment]
Here's what the log in `/var/vcap/sys/log/google_cpi` has for the `delete_vm` call above. Seems like no retry is done?
```
********************
[json] 2018/08/08 02:28:48 DEBUG - Request bytes
********************
{"method":"delete_vm","arguments":["vm-883956d6-0a95-4075-5687-93f616db0598"],"context":{"director_uuid":"90f48ecd-5ae6-4b2e-9c72-af9fa9cc7a65","request_id":"cpi-255401"},"api_version":1}
********************
[json] 2018/08/08 02:28:48 DEBUG - Deserialized request
********************
{delete_vm [vm-883956d6-0a95-4075-5687-93f616db0598]}
********************
[GoogleInstanceService] 2018/08/08 02:28:48 DEBUG - Finding Google Instance 'vm-883956d6-0a95-4075-5687-93f616db0598'
[json] 2018/08/08 02:29:18 DEBUG - CloudError response bytes
********************
{"result":null,"error":{"type":"Bosh::Clouds::CloudError","message":"Deleting vm 'vm-883956d6-0a95-4075-5687-93f616db0598': Failed to find Google Instance 'vm-883956d6-0a95-4075-5687-93f616db0598': Get https://www.googleapis.com/compute/v1/projects/sap-gcp-hcp-cf-live-us30/aggregated/instances?alt=json\u0026filter=name+eq+.%2Avm-883956d6-0a95-4075-5687-93f616db0598: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 173.194.194.84:443: i/o timeout","ok_to_retry":false},"log":""}
```

**Comment by voelzmo** [comment]
As a bonus: Here is a graph showing the occurrences in the last week. This seems to hit us continuously. Graphs show count per hour, so it is not incredibly often, but still often enough to cause trouble.

<img width="1074" alt="screen shot 2018-08-09 at 11 32 44" src="https://user-images.githubusercontent.com/2256887/43890834-1e1537b0-9bc8-11e8-95b2-3bc9a53668ce.png">
