### ISSUE TITLE
Support relative path for `private_key`

### ISSUE THREAD

**Issue by evandbrown** [cloudfoundry-incubator/bosh-google-cpi-release#46]
Per @cunnie in #31, `private_key` does not support relative paths. We should fix that.

**Comment by cppforlife** [comment]
Is this bosh-init's `private_key`? If so it does support it to be relative. Are there any other `private_key`?

**Comment by ljfranklin** [comment]
Thanks in advance (testing slack webhook)!

**Comment by ljfranklin** [comment]
Double thanks in advance (testing hook again)

**Comment by cppforlife** [comment]
i think this issue could be closed. nothing to do.
