### ISSUE TITLE
Could we make some network CPI parameters also changable on VM types?

### ISSUE THREAD

**Issue by dsboulder** [cloudfoundry-incubator/bosh-google-cpi-release#52]
We're coming up on a situation where we want a few VMs in a network to have public IPs, but not the rest of them.  We may also need to tag them differently, depending on our desired firewall rules.  

Could we make the following CPI network params also overridable on a VM type?  Presumably the VM type would take precedence over the network settings.
* ephemeral_external_ip
* tags
* ip_forwarding?

Thank you!

**Comment by evandbrown** [comment]
Awesome. Great idea! I think the VM type overriding the network type make sense. I'll get this in shortly.

**Comment by evandbrown** [comment]
Quick note: #45 incorporated support for `tags` in both places. In that scenario, it merges tags from both network and VM types. Do we want VM to overwrite any network props it specifies?

**Comment by evandbrown** [comment]
@dsboulder Just released in v24.3.0 (https://github.com/cloudfoundry-incubator/bosh-google-cpi-release#cpi)
