### ISSUE TITLE
support global cpi configuration for tags

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-google-cpi-release#78]
to allow tagging of all vms with specific set of tags to enable setting security groups. global tags would be added on top of tags specified via `env` arg in `create_vm`. wdyt about `google.default_tags: [tag1, tag2]`?

cc @evandbrown @dsboulder

**Comment by evandbrown** [comment]
@dsboulder @mrdavidlaing do `default_tags` give you capabilities that 'tag with job name' doesn't?

Otherwise I'm fine with this and happy to add if it's useful.

**Comment by cppforlife** [comment]
@evandbrown this will be useful for setting custom tags director wide (including director), e.g. `staging-blah`. this global cpi configuration (not in vm cloud properties) will enforce tag setting across all machines.

**Comment by johnsonj** [comment]
Closing due to age. Please re-open if it's still relevant.
