### ISSUE TITLE
Unable to ssh into vms

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry-incubator/bosh-google-cpi-release#79]
Trying to ssh into vms using `bosh ssh` results in an error:

```
root@bosh-bastion:~# bosh ssh
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on deployment 'cf' on 'micro-google'
Target deployment is 'cf'

Setting up ssh artifacts

Director task 36
Error 450001: Action Failed ssh: Getting host public key: Unable to read host public key file: /etc/ssh/ssh_host_rsa_key.pub: Opening file /etc/ssh/ssh_host_rsa_key.pub: open /etc/ssh/ssh_host_rsa_key.pub: no such file or directory

Task 36 error
Failed to set up SSH: see task 36 log for details
```

I'm using:
* bosh release 257.9
* google-cpi-release 25.3.0
* stemcell 3262.9

After un-mounting the vm's root disk and mounting it on my bastion vm I was able to check the vm logs:

```
Sep  9 07:51:39 localhost sshd[4313]: fatal: No supported key exchange algorithms [preauth]
Sep  9 07:52:04 localhost sshd[4320]: error: Could not load host key: /etc/ssh/ssh_host_rsa_key
Sep  9 07:52:04 localhost sshd[4320]: error: Could not load host key: /etc/ssh/ssh_host_dsa_key
Sep  9 07:52:04 localhost sshd[4320]: error: Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Sep  9 07:52:04 localhost sshd[4320]: error: Could not load host key: /etc/ssh/ssh_host_ed25519_key
```
And indeed, ssh host keys are not there:

```
root@bosh-bastion:~/test/etc/ssh# ls -la
total 256
drwxr-xr-x  2 root root   4096 Aug 31 18:13 .
drwxr-xr-x 85 root root   4096 Sep  9 07:52 ..
-rw-r--r--  1 root root 242091 May  5 14:16 moduli
-rw-r--r--  1 root root   1690 May  5 14:16 ssh_config
-rw-------  1 root root   2912 Jun 23 21:29 sshd_config
```

**Comment by frodenas** [comment]
May be we need a new stemcell that includes https://github.com/cloudfoundry/bosh/pull/1390? I don't see that fix on stemcell 3262.9:

```
root@bosh-bastion:~/test/root# more firstboot.sh
#!/bin/sh

rm /etc/ssh/ssh_host*key*

dpkg-reconfigure -fnoninteractive -pcritical openssh-server
dpkg-reconfigure -fnoninteractive sysstat
```

**Comment by voelzmo** [comment]
Probably related: https://github.com/cloudfoundry/bosh/issues/1399

**Comment by cppforlife** [comment]
yup will be backporting these changes for 3262.x shortly: https://www.pivotaltracker.com/story/show/129982207

**Comment by RochesterinNYC** [comment]
Any update on when there would be a release with this fix?

**Comment by cppforlife** [comment]
@RochesterinNYC @frodenas published 3262.14. core took over google stemcells now.

**Comment by RochesterinNYC** [comment]
@cppforlife I see, when will it be available via https://storage.googleapis.com/bosh-cpi-artifacts/light-bosh-stemcell-3262.14-google-kvm-ubuntu-trusty-go_agent.tgz

Or does your second statement mean that the stemcells are now hosted and updated somewhere else?

**Comment by RochesterinNYC** [comment]
@cppforlife I see, when will it be available via https://storage.googleapis.com/bosh-cpi-artifacts/light-bosh-stemcell-3262.14-google-kvm-ubuntu-trusty-go_agent.tgz

Or does your second statement mean that the stemcells will be hosted somewhere else?

**Comment by RochesterinNYC** [comment]
Update: never mind, it seems that they can be downloaded/uploaded via bosh.io now: http://bosh.io/stemcells/bosh-google-kvm-ubuntu-trusty-go_agent Thanks!
