### ISSUE TITLE
Failed to find missing persistent disk in `bosh cck` and subsequent `bosh deploy`

### ISSUE THREAD

**Issue by jfmyers9** [cloudfoundry-incubator/bosh-google-cpi-release#87]
After deleting a persistent disk from the GCP UI, I was unable to return to an operational state through a `bosh cck` or `bosh deploy`.

I believe this is related to a missing `has_disk` here: https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/tree/master/src/bosh-google-cpi/action.

**Comment by cppforlife** [comment]
cc @evandbrown @dsboulder

**Comment by cppforlife** [comment]
bump @evandbrown

**Comment by evandbrown** [comment]
Ack. Will get this in today.

**Comment by evandbrown** [comment]
[25.6.0][25.6.0] is out and addresses this issue.

[25.6.0]: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-google-cpi-release?v=25.6.0
