### ISSUE TITLE
CPI installation fails on macOS Sierra

### ISSUE THREAD

**Issue by coreyti** [cloudfoundry-incubator/bosh-google-cpi-release#92]
It looks like[^1] various releases of Golang have compilation problems on macOS Sierra. I've built a dev version of the CPI release with Go v1.7.1, and found that work. I plan to submit a PR, bumping Go for Darwin and Linux... just wanted to open this up for discussion first.

[^1]: Based on
  - https://github.com/golang/go/issues/17335
  - https://github.com/golang/go/issues/17182
  - https://github.com/golang/go/issues/16352

**Comment by voelzmo** [comment]
yup, golang 1.7.1 is the only one that actually works.

**Comment by coreyti** [comment]
...recalling now that I would not be able to complete this fix as a PR, as I do not have credentials for the blob store. /cc @evandbrown
