### ISSUE TITLE
Cannot create vms with persistent disk set to 1000GB

### ISSUE THREAD

**Issue by jvshahid** [cloudfoundry-incubator/bosh-google-cpi-release#98]
Looks like the payload that the CPI receives back from the gcp api cannot be marshaled properly into an int because the value was marshaled using floating point syntax.

[This Gist](https://gist.github.com/jvshahid/9173cde695ef5525f91579ce85ad9d83) has the output from the  `bosh deploy` step.

**Comment by cppforlife** [comment]
@evandbrown Potentially similar to https://github.com/cloudfoundry/bosh-agent/commit/d11adb42a008859408483d527d4af4e73cd12819

**Comment by evandbrown** [comment]
Ack. Will get the fix in this morning and update this issue when a build makes it through the pipeline. Thanks for reporting, @jvshahid.

**Comment by evandbrown** [comment]
[Dev build 0.0.223](http://storage.googleapis.com/develop-bosh-cpi-artifacts/bosh-google-cpi-0.0.223.tgz) resolves this issue. I'll have an official patch release available once it goes through the prod pipeline (~2 hours from now).

**Comment by evandbrown** [comment]
Release [25.6.1](http://bosh.io/d/github.com/cloudfoundry-incubator/bosh-google-cpi-release?v=25.6.1) resolves this.
