### ISSUE TITLE
Poor error when specified external IP is missing

### ISSUE THREAD

**Issue by krishicks** [cloudfoundry-incubator/bosh-google-cpi-release#99]
When trying to use a global external IP I received the following error:

```
Error 100: VM failed to create: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].accessConfigs[0]': ''. Specified external IP address not found., invalid
```

There are two problems here:

1. The error is more busy than it needs to be, making resolution potentially difficult (accessConfigs[0]?)
1. It's not clear that the IP address has to be available in the same region, not a global address

**Comment by evandbrown** [comment]
Thanks, Kris! Fix is on the radar.

**Comment by johnsonj** [comment]
Closing due to age. Please re-open if it's still interesting.
